### ISSUE TITLE
If latest pipeline is not finished fallback to previous one

### ISSUE THREAD

**Issue by axelthimm** [timoschwarzer/gitlab-monitor#122]
Hello,

we have pipelines that do continuous testing. As such most of the time the pipeline is in a running state. The real interesting pipeline is the pipeline before the currently running.

Therefore it would be nice to be able to configure the monitor to skip the running pipelines and only show the latest non-running pipeline. AFAICT there is not configuration that allows that (I'd be glad to be wrong!).

Many thanks, Axel.

**Comment by timoschwarzer** [comment]
Hi Axel,

I've added a new option which you can use like this in your config:

```yaml
projectConfig:
  '*':
    historyCount: 3  # Display at least 3 pipelines per ref
```

Please consider [sponsoring me on GitHub](https://github.com/sponsors/timoschwarzer/) if your team found this project useful :)
