### ISSUE TITLE
Feature: Option to show last commit

### ISSUE THREAD

**Issue by motcke** [timoschwarzer/gitlab-monitor#128]
For my use case, it would be very much helpful if for each pipeline I'll be able to see last commit details (message, committer name/email, time). 
This way I'll be able to understand what feature was pushed and track the progress. Also, in case the pipeline failed it's easier to figure out the reason.

**Comment by motcke** [comment]
Here's one way of how the configuration will look for this feature:
```yaml
# Do not show commit (same as without the feature)
commit: null
```
or
```yaml
commit:
    # don't show commit id
    id: false

    # Show only the first two (if exist) and limit the line length to 100.
    message:
        maxLines: 2
        maxLineChars: 50

    # Show committer name but not the email
    author:
        name: true
        email: false

    # Show commit time
    time: true
```
